# Generated by Django 4.0.3 on 2022-05-10 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='import_vin',
        ),
    ]
